### ISSUE TITLE
Support all Philips hue lights, including on/off and dimmables

### ISSUE THREAD

**Issue by benknight** [benknight/hue-alfred-workflow#10]
So the way I fixed #9 was by just ignoring these lights, but the workflow should support them because otherwise it's not very useful for people that have these on their lighting system.  Should be pretty easy to support.  Refer to this data export:

http://f.cl.ly/items/2U0u1h2G1l16253J3U1H/hue_CLIP_API_Debugger.txt

**Comment by joshbetz** [comment]
> I can imagine quite frustrating for anyone who's trying to use this workflow when their lighting system contains bulbs other than color bulbs.

:+1:

**Comment by romainpoirier** [comment]
Thank you for this fix that will change my everyday life!

**Comment by benknight** [comment]
I've added support to master but have yet to release.  Would love to have a few people beta test it first!

**Comment by benknight** [comment]
@romainpoirier @joshbetz can you help me test out a beta version that fixes this bug?

Here's the download link: http://cl.ly/1S2A0T1r0A39/Philips%20Hue%20Controller%20v2.4-beta.alfredworkflow

Let me know if you're able to control your dimmables now!

**Comment by romainpoirier** [comment]
Thanks for this update ! With my three Philips Hue Lux bulbs, almost everything is working fine.

But the Presets are not working for me. I tried to save some with different values, but each time the same value was recorded. I started, but when I call a preset, it not start.

Note that the Set color to... et Set effect .. are useless for me, as I'm using Philips Hue Lux bulbs. Perhaps it could be interesting to be able disable this unusable options.

Also, perhaps it could be interesting to set a length of blinking time for the reminder. Sometimes the reminder is not urgent, sometimes it is.

**Comment by benknight** [comment]
Thanks @romainpoirier.  I've since removed the options that don't make sense for non-color bulbs.

You were totally right about the presets not working, thanks for helping me find this.  I should really get some of my own Lux bulbs to test with.

Here's a new release that should hopefully fix all these issues:
https://github.com/benknight/hue-alfred-workflow/releases/download/v2.4-beta2/Philips.Hue.Controller.v2.4-beta2.alfredworkflow

**Comment by romainpoirier** [comment]
Thank you Benjamin for this update !

One suggestion for a future improvement : if you set color to or effect to
or brightness to and the bulbs are if the lights are not already turned on,
perhaps it could be useful to automatically turn them on after this action.

Lux bulbs are not so expensive compare to regular Hue bulbs  :-)

2015-02-04 6:55 GMT+01:00 Benjamin Knight <notifications@github.com>:
