### ISSUE TITLE
set-bridge successfull, but shows "Bridge connection failed" on next command

### ISSUE THREAD

**Issue by dolbertz** [benknight/hue-alfred-workflow#20]
I'm running Yosemite 10.10.1, Alfred 2.5.1 (308) and the current version of your workflow. I did not update, as I just set up hue at my house.

-hue set-bridge gives a "success"-Notification, but when I enter "hue", it just shows me that "Bridge connection failed" and I should use "-hue set-bridge" first. I also tried that twice, but still the same outcome.

I also opened up the console, but could not see any errors. What can I do to help you figuring this out? I also use homebrew and a different php version than what comes with Yosemite. Is there any script I could run on the command line to see what's going on?

**Comment by benknight** [comment]
@dolbertz, sorry for the delay in getting back to you.

I just tried a clean install of 2.3 and I wasn't able to reproduce the issue described.

It seems like the workflow is finding your bridge but when the connection is timing out when it attempts to communicate with it.  This is difficult to troubleshoot remotely, but let's try this first:

1. Go to `https://www.meethue.com/api/nupnp` this will show some code that contains the IP address of the bridge on your local network, something like:```[{"id":"001788fffe0a3ece","internalipaddress":"192.168.1.123","macaddress":"00:17:88:0a:3e:ce","name":"Philips hue"}]```
2. Navigate to `http://<internalipaddress>/debug/clip.html`, replacing <internalipaddress> with whatever the bridge's IP (in the example above it would be `http://192.168.1.123/debug/clip.html`).
3.  Tell me if that loads the API debug tool.
4.  If it does, try running through the steps outlined here: `http://www.developers.meethue.com/documentation/getting-started`

I'm hoping you might figure out what's going on at some point along the way there.  If you're able to send commands using the API debug tool, yet the workflow still isn't working, then I would be concerned that perhaps you're not the only one and would ask to debug your setup further and would probably proceed by sending you a few commands to execute in your terminal.

**Comment by dolbertz** [comment]
Thanks for your reply!

I could successfully run the debug console: create a new developer, see a list of my "lights" and turn one off and on.

That also worked, when I used the username your workflow created and stored in ~/Library/Application Support/Alfred 2/Workflow Data/hue-alfred-workflow/settings.json. But the file ~/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/hue-alfred-workflow/lights.json only contains an empty hash: {}.

Please let me know how I can further help you in debugging this!

There is a debug.log inside the workflow source code, but the last entry is from 2014-10-23. You probably should remove it from the package :)

Here some info about my setup that might be helpful:
> python --version
Python 2.7.6

> which python
/usr/bin/python

Thanks!

**Comment by benknight** [comment]
What do you get back when you run this API command: `GET /api/<username>` in the debug tool?

**Comment by dolbertz** [comment]
I sent you the information via email as I rather would not share that informaton with everybody.

**Comment by benknight** [comment]
Thanks! I took a look over your API data and the reason became clear:  you have nothing but dimmable plug-ins on your Hue system, and sadly the workflow currently only supports Hue bulbs.  These are the many kinds of lights that are supported by the Hue system:  http://www.developers.meethue.com/documentation/supported-lights

I have a ticket to add support here: #10. It's my top priority at this point and I plan on pushing an update for this soon, hopefully within a week.  Thanks for your patience!

**Comment by benknight** [comment]
Hey Dirk,

Can you uninstall any previous versions of the workflow, install the one
attached, and tell me if it works for you?

Thanks!
Ben

**Comment by dolbertz** [comment]
I now can switch my lights on/off and also set the brightness! Great!

I didn't use the presets and I don't mind that the workflow shows options that I cannot use (eg. "Color Loop"-Effect).

Thanks!

**Comment by benknight** [comment]
Oh thanks for reminding me about the effects.  I'll make sure I get rid of
those for dimmables.  Glad it worked!
