### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by hairybridget** [benknight/hue-alfred-workflow#26]
The workflow is able to connect to my hub and pull up my device list, items show accurate on/off and color status, but none of the commands are functioning.  Any tips?

**Comment by benknight** [comment]
@hairybridget thanks for the report. I need more information to get an idea of what's going on. Are you able to take any screenshots or make a video? Quicktime makes it really easy to record your screen.  Also you can go to the workflow in the Alfred Preferences, click the bug icon (picture below), then follow the same steps where you try to set the lights, and tell me if anything appears in the log?

![image](https://cloud.githubusercontent.com/assets/786691/11881322/f4e57bae-a4ba-11e5-8f3b-424595d36b49.png)

**Comment by benknight** [comment]
@hairybridget I'm going to close this since I have no other reports and no follow up information to investigate your information.  If you are still having this problem, feel free to open the issue.
