### ISSUE TITLE
Move presets to first level

### ISSUE THREAD

**Issue by leocrespo** [benknight/hue-alfred-workflow#27]
It's much more useful to have presets on the first level and individual lights on the second. Nobody changes lights individually, we all change lights via presets, or scenes, or groups. 

One never goes "turn of lamp number 8", but rather "load scene sleep", or "turn off group bedroom"

**Comment by benknight** [comment]
I can see how that makes sense for some users.  I personally do use the workflow to control individual lights often, and I name mine things like "Desk" and "Bed" instead of by numbers.  But I'll take that into consideration, thanks!

**Comment by benknight** [comment]
@leocrespo I have a suggestion for you.  If you go to the Alfred Preferences and edit the Hue workflow, you can press the "+" to add your own custom "Hotkey" trigger, and configure it as follows:

![image](https://cloud.githubusercontent.com/assets/786691/13038240/30ce8436-d345-11e5-9e1e-d7eb23932633.png)

What this does is automatically opens your presets based on a hotkey combination.  In the example above I used Shift+Command+P but you can set it to anything you like.

What's great about Alfred Workflows is they're complete customizable!
