### ISSUE TITLE
Color picker 

### ISSUE THREAD

**Issue by tungnh91** [benknight/hue-alfred-workflow#34]
After a color is being picked from the color picker, Alfred disappear after hitting done. Command was not executed.

**Comment by benknight** [comment]
@tungnh91 are you using Alfred 2 or 3?  Currently broken in Alfred 3, will be fixed in next release (2.5).

**Comment by tungnh91** [comment]
@benknight I'm using Alfred 3, looking forward to the update! Thanks for the all the hard work.

**Comment by benknight** [comment]
You can fix it yourself by editting the workflow.  Double click the first "/usr/bin/php" Run Script actions and in the PHP code change where it says "Alfred 2" to "Alfred 3"
