### ISSUE TITLE
No json object could be decoded

### ISSUE THREAD

**Issue by LETRA** [benknight/hue-alfred-workflow#43]
Hi. I have a problem for a few days. I thought an update would fix it, but I see that I am the only one who has reported this problem.

When I start Hue Controller I get the message "no json object could be decoded". I hope you can help out.

Thank you. 
<img width="704" alt="captura de pantalla 2018-07-12 a las 22 44 07" src="https://user-images.githubusercontent.com/16805254/42658958-12f06fbe-8627-11e8-8592-9207fc868b01.png">

**Comment by brichards** [comment]
I've just encountered this myself in the past week.

@benknight Any ideas where I could begin to look to help debug?

**Comment by benknight** [comment]
@brichards can you open Alfred Preferences, go to Workflows, select Philips Hue Controller, select the little debug icon in the top right, then trigger the workflow by typing "hue" in Alfred, and copy and paste whatever output occurs in the debug log?

<img width="1440" alt="Screen Shot 2019-04-27 at 2 06 26 PM" src="https://user-images.githubusercontent.com/786691/56846160-bc7b8a80-68f5-11e9-89eb-6850f9583d65.png">

**Comment by brichards** [comment]
Well isn't that slick. I remember seeing the bug icon when first knocking around Alfred years ago, then promptly forgot about it, it would seem.

Here's what I'm getting:
```
[2019-04-29 09:59:33][input.scriptfilter] Queuing argument ''
[2019-04-29 09:59:34][input.scriptfilter] Script with argument '(null)' finished
[2019-04-29 09:59:34][ERROR: input.scriptfilter] Code 1: 09:59:33 workflow.py:2249 DEBUG    workflow version: 3.0.0
09:59:33 workflow.py:1657 DEBUG    reading settings from /Users/brian/Library/Application Support/Alfred 3/Workflow Data/hue-alfred-workflow/settings.json
09:59:33 workflow.py:2532 DEBUG    Update check not due
09:59:33 workflow.py:1884 DEBUG    loading cached data: /Users/brian/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/hue-alfred-workflow/__workflow_update_status.cpickle
09:59:33 workflow.py:2462 DEBUG    update_data: {u'available': False}
09:59:34 workflow.py:1657 DEBUG    reading settings from /Users/brian/Library/Application Support/Alfred 3/Workflow Data/hue-alfred-workflow/settings.json
09:59:34 workflow.py:2267 ERROR    No JSON object could be decoded
Traceback (most recent call last):
  File "logic/packages/workflow/workflow.py", line 2260, in run
    func(self)
  File "/Users/brian/Dropbox/App Settings/Alfred.alfredpreferences/workflows/user.workflow.25AA811F-202B-4A60-87EC-31D89FC1BBBC/logic/filters.py", line 456, in main
    items = hue_index_filter.get_items()
  File "/Users/brian/Dropbox/App Settings/Alfred.alfredpreferences/workflows/user.workflow.25AA811F-202B-4A60-87EC-31D89FC1BBBC/logic/filters.py", line 102, in get_items
    lights = utils.get_lights()
  File "logic/utils.py", line 85, in get_lights
    load_full_state()
  File "logic/utils.py", line 43, in load_full_state
    data = r.json()
  File "logic/packages/requests/models.py", line 643, in json
    return json.loads(self.text or self.content, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
09:59:34 workflow.py:2290 DEBUG    workflow finished in 0.159 seconds```

The error is triggered when `load_full_state()` attempts to pull back all the data from the bridge. The reason, I realized, is because my bridge changed IP addresses a week or so back when I rebooted everything in my router cabinet. The workflow settings had the old IP address logged, which is now a different device, and was getting a 404 response rather than a JSON object.

Seems like perhaps an additional exception check is needed here for these unlikely occurrences?

**Comment by benknight** [comment]
@brichards excellent, I agree with your assessment of the issue :D Feel free to submit a pull request, or I can look at this issue some time in the future.

If future readers come across this issue and it's still not resolved, uninstalling and reinstalling the workflow should work in the case that the bridge's IP address changed.

**Comment by merchako** [comment]
In the meantime, the it's easier to delete (or rename) `~/Library/Application Support/Alfred 3/Workflow Data/hue-alfred-workflow/settings.json` than it is to replace the IP address stored. So the brainless approach is:

1. Rename or delete the `settings.json`,
2. Press the sync button on your Hue hub,
3. Reinitialize `hue-alfred-workflow` by Alfreding `hue +` the only option.
