### ISSUE TITLE
Filter out group scene results by typing name (not currently working)

### ISSUE THREAD

**Issue by Baggydawg** [benknight/hue-alfred-workflow#49]
After activating the workflow with the keyword, the dropdown list of options is filtered out as I continue typing the next action.

However for some reason on the group scene selection drop down, results aren't filtered out even as I type out their names.

I only set preconfigured scenes with Hue, so I created a keyword that brings me to this scene setting, and ideally each time I'd like to just continue typing the name of the scene as the others are filtered out (as opposed to having to manually scroll through and select the correct one).

How can I do this?

**Comment by benknight** [comment]
@Baggydawg can you try updating to the latest version v3.0.2 and see if that fixes? I recommend clearing out your settings via `hue workflow:reset`

**Comment by Baggydawg** [comment]
I just delete the whole workflow and package contents, redownloaded from here, reinstalled and updated to the latest version.

It's connected again however same result, the scenes aren't filtered out as I type which is annoying.

**Comment by benknight** [comment]
@Baggydawg this has been fixed in v3.0.3

**Comment by magoz** [comment]
I'm on v3.0.3 and it's not working for me either.
I reinstalled and also ran `hue workflow:reset`. I'm on macOS 10.15.5.

Am I missing something @benknight?

Thanks.

**Comment by Baggydawg** [comment]
This is working for me now, thanks.

@magoz I deleted the workflow entirely, and set it up again from scratch. Give that a shot.

**Comment by magoz** [comment]
Did you do something special when deleting the workflow? Is there any other way to remove the workflow entirely other than just right-click on delete workflow from Alfred's preferences?

**Comment by Baggydawg** [comment]
I just deleted it from inside Alfred Pref, then also deleted the downloaded zip + unzipped contents.

When setting up you'll obviously have to re-press the bridge button. But it worked for me, so I don't see why it wouldn't for you.

**Comment by magoz** [comment]
Yeah, that's what I did, but the results still don't filter out when typing. 
I've did some testing and while the rooms/lights don't filter out, the actions do (screenshots below).

<img width="619" alt="Screen Shot 2020-07-06 at 11 14 15" src="https://user-images.githubusercontent.com/9190753/86577107-0b04ca00-bf7a-11ea-917c-6a8081ecbea2.png">

<img width="619" alt="Screen Shot 2020-07-06 at 11 14 38" src="https://user-images.githubusercontent.com/9190753/86577127-122bd800-bf7a-11ea-87ec-b1dd5a8d9211.png">

Is that the intended behavior?
I'm happy to provide any more details to help debug this.

**Comment by magoz** [comment]
I still can't make it work.

@benknight is this the intended behavior? 

> Yeah, that's what I did, but the results still don't filter out when typing.
> I've done some testing and while the rooms/lights don't filter out, the actions do (screenshots below).
> 
> <img alt="Screen Shot 2020-07-06 at 11 14 15" width="619" src="https://user-images.githubusercontent.com/9190753/86577107-0b04ca00-bf7a-11ea-917c-6a8081ecbea2.png">
> 
> <img alt="Screen Shot 2020-07-06 at 11 14 38" width="619" src="https://user-images.githubusercontent.com/9190753/86577127-122bd800-bf7a-11ea-87ec-b1dd5a8d9211.png">
> 
> Is that the intended behavior?
> I'm happy to provide any more details to help debug this.

**Comment by Ostendorf** [comment]
Hello, just installed v3.0.6 and I have this same problem. I connected the workflow to Hue Bridge and that works, but it does not filter the results. I can only use it by selecting the items manually. Would appreciate it if the filter functionality can be fixed. Tell me if I can help in any way.
