### ISSUE TITLE
Got a new Mac and transferred all the data over but, I can't use the hue controller

### ISSUE THREAD

**Issue by chessemuffin** [benknight/hue-alfred-workflow#60]
I keep getting this error message, I have tried deleting and reinstalling the workflow but it won't take me back to the set-up menu. I think its something to do with the transferring of data from my old intel mac to my new silicon mac, and something may have gotten messed up. I love this workflow and it would be awsome if anyone has a fix.

Thanks,

![image](https://user-images.githubusercontent.com/89578599/139405015-ef97e7c7-5877-484e-92a4-2549f7b1fa80.png)

**Comment by benknight** [comment]
Closing this with the recommendation to remove workflow and reinstall.
